name: Format

on:
    push:
        branches: [gh-pages]
    pull_request:
        branches: [gh-pages]

jobs:
    format:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [23.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run format:check
